### PR TITLE
Fix #67: solved a bug where reconnect time would be waited even for succesful connections

### LINKED ISSUE #67: Tests using a RELP server are slow
**Describe the bug**

Tests using a RELP server take a long time because the first connect() call to ManagedRelpConnection fails, starting a reconnect loop with a sleep time of `relp.reconnectInterval`. Not sure if this happens outside of the testing environment.

Very noticeable when creating multiple connections back to back.

**Expected behavior**

Should connect straight away to speed up tests.

**How to reproduce**

Run any test in EndToEndTest.java, notice that it takes just a bit longer to run than the reconnectInterval.

**Screenshots**

**Software version**

**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

Workaround is to set  `relp.reconnectInterval` to a lower value in unit tests.

### PR DESCRIPTION
**Pull request by 51-code**
Solves issue #67.

There was a bug introduced in #66 where the `Thread.sleep()` meant to be called for a failed attempt at connecting would also be called once for a successful attempt.

Moved the sleep function call inside the catch block where the failed connection is handled.

### CODE REVIEW

File: src/main/java/com/teragrep/lsh_01/pool/ManagedRelpConnection.java [hunk 1]
```diff
@@ -52,13 +52,13 @@ private void connect() {
...
-            try {
-                Thread.sleep(relpConnection.relpConfig().relpReconnectInterval);
-            }
-            catch (InterruptedException e) {
-                LOGGER.error("Reconnect timer interrupted, reconnecting now");
+                try {
+                    Thread.sleep(relpConnection.relpConfig().relpReconnectInterval);
+                }
+                catch (InterruptedException exception) {
+                    LOGGER.error("Reconnect timer interrupted, reconnecting now");
```
Comment (MoonBow-1) [inline src/main/java/com/teragrep/lsh_01/pool/ManagedRelpConnection.java:60]: I'd change the error from: `"Reconnect timer..."` to `"Reconnection timer..."`

File: src/test/java/EndToEndTest.java
Comment (MoonBow-1) [inline src/test/java/EndToEndTest.java:1]: Can't say much about this change, but this seems to be the root cause of the issue the commit fixes

File: src/test/java/RebindTest.java
Comment (MoonBow-1) [inline src/test/java/RebindTest.java:1]: Same as in [`src/test/java/EndToEndTest.java`](https://github.com/teragrep/lsh_01/pull/71/files#diff-a52e8b9a716c62e7db1202f82b5bd518853a52281b1bc644751cb30918a3a00d)

**Review by MoonBow-1 — COMMENTED** [review]
Minor grammar suggestion, otherwise this PR looks good

**Review by MoonBow-1 — APPROVED** [review]
LGTM now

**Review by kortemik — APPROVED** [review]
